### ISSUE TITLE
new timestamps are integers

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#10]
timestamps in geolocation viewer and in couchDB new records are just an integer number, need to be formatted as human readable date-time ("2016-04-11 05:34:20.000GMT-5")

**Comment by relevante** [comment]
These are for linking child events to the data stream and are not intended for human consumption. Storing them as UTC timestamps eliminates possible time zone discrepancies and makes comparisons faster.
