### ISSUE TITLE
Exit side menu

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#20]
When bringing up the side menu (via the hamburger), I keep wanting to swipe left to return to the main screen. As of now, I should be tapping the hamburger instead. But can we make swiping gestures do the same?

**Comment by tigoe** [comment]
@jcousins @relevante will look into it. If it's complicated to do, we could enlarge the hamburger target

**Comment by jcousins** [comment]
Made some clear adjustments to make the exit interaction non-ambiguous.

**Comment by tigoe** [comment]
Seems clearer to me. @difiore and @kchiou should look and comment.
