### ISSUE TITLE
Geolocation viewer

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#22]
My geolocation viewer shows a failure (message below) on my Google Nexus 5. I double checked that location settings were on (tested using both the GPS+WiFi/Bluetooth/Cellular setting and the GPS-only setting) and confirmed that I was getting a satellite fix using the Android app GPSTest. I restarted the EthoApp after each check and got the same result.

```
Failure!
{}
```

**Comment by tigoe** [comment]
Geoloc viewer is a diagnostic tool only, could be taken out at this point.
