### ISSUE TITLE
Form labels

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#23]
Can clicking on form labels highlight/select the corresponding form elements? This is especially useful for the dropdown "select" menus where the label and values are on opposite sides of the screen.

**Comment by tigoe** [comment]
@jcousins looking into it 7/15/16

**Comment by jcousins** [comment]
This would be kind of an odd hack to html (also, referenced here as non-trivial… http://stackoverflow.com/questions/19913171/how-to-trigger-the-html-select-onclick-event-activates-select-dropdown-with-opt). 

What I did instead was to dial back how much of button-like styles were being stripped back in the CSS. Now the target is a lot more obvious, and it’s revealed how large it actually is. Big improvement.

**Comment by tigoe** [comment]
option select menus appear to be working much better for me.
