### ISSUE TITLE
Hitting the home button

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#24]
Hitting the button with my finger on the Google Nexus 5 phone is pretty difficult (i.e., to return to list of diaries). It takes a few tries for me to get it.

**Comment by tigoe** [comment]
Same as #30. Has to do with the fact that the target you can click on is too small. Probably solve by enlarging breadbumb bar.

**Comment by jcousins** [comment]
Comments here also relate to #30 (duplicate comments)... Also, important note, that these will likely also be helped once #39 is completed (provided the new version corrects for status bar issues).

Made breadcrumb bar is a hair larger now so targets are larger, but I also did a lot of work on the Home button to make sure it layers in a fashion that exposes more of it to a touch interaction. 

In addition to all of this, there are some issues being created by the iOS status bar at the top (the bar from the app that has the time, signal strength, battery, etc). Even though the background for this bar is clear in this app, it’s still physically there ("physically" in the virtual sense) and it’s almost certainly been blocking touches things behind it.  

Am going to create a new issue that Cordova needs updating OR to be modified.
