### ISSUE TITLE
on iOS: map tab doesn't show up

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#26]
seems to be wrapped past right edge of screen on an iPhone 5S. as a result, map not seen
- here are two images of the map tab on an iPhone 5S seemingly wrapping under the rest of the tabs on two different screens

![img_1355](https://cloud.githubusercontent.com/assets/5214081/15557281/d74c1e6c-2297-11e6-948c-a12387716a6f.jpg)
![img_1356](https://cloud.githubusercontent.com/assets/5214081/15557449/a7a11fae-2298-11e6-964e-a34e241250a7.jpg)

**Comment by tigoe** [comment]
Old bug, has been fixed.
