### ISSUE TITLE
iOS: map issues

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#29]
- on map screen, when I move a colored contact, get one list of fields in dialog box and a ghosedt/greyed out version of the original point; but can also move greyed contact and see a different list of fields; this happens when moving "marked trees" within a contact, too. Do these colored versus greyed pins correspond to the current object (e.g., marked tree) and the parent object (contact)?
- also, still no persistence in the "new locations" of these moved objects.

**Comment by tigoe** [comment]
7/15/16 closed, this is related to issue #33
