### ISSUE TITLE
iOS: sluggish breadcrumb navigation

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#30]
- navigation to "earlier" fields on breadcrumb is sluggish and takes multiple presses; maybe the titlebar/breadcrumb bar should be taller?

**Comment by tigoe** [comment]
7/15/16: make breadcrub bar larger so it's not occluded by iOS top bar. C&S will look into this.

**Comment by jcousins** [comment]
Comments here also relate to #24... Also, important note, that these will likely also be helped once #39 is completed (provided the new version corrects for status bar issues).

Made breadcrumb bar is a hair larger now so targets are larger, but I also did a lot of work on the Home button to make sure it layers in a fashion that exposes more of it to a touch interaction. 

In addition to all of this, there are some issues being created by the iOS status bar at the top (the bar from the app that has the time, signal strength, battery, etc). Even though the background for this bar is clear in this app, it’s still physically there ("physically" in the virtual sense) and it’s almost certainly been blocking touches things behind it.  

Am going to create a new issue that Cordova needs updating OR to be modified.
