### ISSUE TITLE
in newest version, contacts etc triangle fold-down not working...

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#36]
2016-06-05 -- I pulled latest repos and rebuilt and, running in a browser on the desktop, the accordian fold for contacts, etc., not working; also ADDING contacts, collections, etc. no longer working :(

**Comment by jcousins** [comment]
Hey Tony, Are you working within an existing diary while attempting to test the accordion folds and the various add functionalities?

**Comment by difiore** [comment]
yep, that's how I was doing it... maybe I should instead start with a 
NEW diary?

**Comment by jcousins** [comment]
Yeah, try that and let us know

**Comment by difiore** [comment]
tried that... same issue -- contacts not being created

**Comment by jcousins** [comment]
What device is this, an iPhone?

**Comment by jcousins** [comment]
Also, what database?

**Comment by difiore** [comment]
No, just in the browser (Chrome)

**Comment by difiore** [comment]
database is "tonytest2"

**Comment by jcousins** [comment]
Ok, and you updated both the framework and project-app? It's probably a good idea to also clear your browser cache.   CSS styles can sometimes be oddly sticky and the absence of updates to them could potentially cause the javascript to fail if it's dependent on it in some way.

**Comment by jcousins** [comment]
I just ran through a test with Nick and he was able to add new content, but he saw the same accordion issue. We were both using Chrome, but were running different modes. Once he switched his browser to "Device Mode" it all worked for him. In this mode the desktop browser will have a bit more specificity wrt interactive events that are mobile-only, things like touches. I bet this means it will also work ok on the mobile devices as is. 

For changing your desktop/laptop Chrome browser to "Device Mode" load the app into Chrome in the normal way. Once it's loaded, simultaneously press Command+Option+J and that will pop open the developer mode. Once in that mode, you can select the device mode icon and that will make the browser recognize more mobile events. The attached image shows what it looks like once you've opened developer mode and selected device mode.

<img width="1034" alt="screen shot 2016-06-06 at 3 55 46 pm" src="https://cloud.githubusercontent.com/assets/455174/15835880/172ff852-2c00-11e6-9b79-ec654b0a8810.png">

**Comment by difiore** [comment]
Thanks guys -

[From the airport in Houston en route to Quito :) ]
- Doing this make the accordion work, but it's still not creating new contacts.
- Also, no tracks, etc, are showing up in the map tabs for any of the diaries, contacts...

Other suggestions?
Best,
T

# 

Dr. Anthony Di Fiore
Professor and Chair

Department of Anthropology
University of Texas at Austin
2201 Speedway Stop C3200
Austin, TX 78712

Email: anthony.difiore@austin.utexas.edu
Phone: 512-232-2183

#

**Comment by jcousins** [comment]
This should work. I'm not even able to replicate the issue. It did have one issue previously (in early June or late May), but that was probably long ago fixed. It’s important to be sure the Chrome browser is in the right mode to read the touches.
