### ISSUE TITLE
Display bug for hamburger menu

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#4]
Posted for Tony:

Currently, when choosing the hamburger and selecting settings from non "diary" screen, the settings interface opens in full screen mode in front of the non diary screen, but others items from the hamburger menu open up behind the nondiary screen (so we see only the left edge of what was opened from the hamburger). It would be very nice if, when you open the hamburger and choose something there, that it open in only the "right" side of the screen and, when closed, we return to what was there before. I.e., choose something from the hamburger menu, it opens on the right, then returns you to the same place when closed.

**Comment by tigoe** [comment]
This is related to bug #5. Closing and merging the two.
