### ISSUE TITLE
Remarks timestamp

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#7]
Posted for Tony:

The clock button at the bottom of Remarks nicely enters a timestamp in "HH:MM" format, but it would make sense to have this enter a complete datetime stamp "YYYY-MM-DD HH:MM:SS" and with some kind of tag around it (e.g., bracketed in some way "[...]" or "<...>"

**Comment by kchiou** [comment]
(Kenny now). I agree that the datetime info should be there for remarks. The format @difiore gave is reasonable under the hood, but I think the displayed format should be in a more human-readable format.

**Comment by tigoe** [comment]
Agreed with Kenny, human-readable format would be better.

**Comment by difiore** [comment]
To me, YYYY-MM-DD HH:MM:SS **_IS**_ human readable :)

HH:MM:SS is perhaps better.

Date and time formatting maybe (down the road) could be a user-defined 
setting. The current date format (MM/DD/YY) is confusing for 
international users (many non US sites use DD/MM/YY).

**Comment by kchiou** [comment]
I would suggest something like this is most readable. Switching in settings is good for international users. I know we can all probably read YYYY-MM-DD HH:MM:SS timestamps without too much trouble, but not all users can.

"April 10, 2016 @ 11:50:25"

**Comment by kchiou** [comment]
Or look at this issues thread itself. "kchiou commented a minute ago" is pretty useful to me as a UI user. If there are well-supported strategies for human-readable times, I think we should use them.

**Comment by tigoe** [comment]
Date formatting is a solved problem in JS. We can use any one of many options, choose one:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by difiore** [comment]
right, since easy options are available, it makes sense (at some point) 
to have the user specify what they would like. right now, "remarks" is 
just a text field, so if there are multiple timestamps in there, it 
won't be as straightforward to parse out). I may make sense (as some 
point?) to treat remarks as an array.

**Comment by difiore** [comment]
we on for 9 am?

I need some github help ;)
