### ISSUE TITLE
Clicking home button fails on some screens

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#8]
When I'm in map or timeline view at any point in the breadcrumb trail, it seems that clicking on the home screen doesn't have the expected behavior (returning to home screen). It works fine from Data or Remarks views. My console gives the error:

```
bundle.js:79955 Uncaught TypeError: previousTab.loseFocus is not a function
```

**Comment by relevante** [comment]
Fixed in ethoinfo-framework 50ae4a2
